### ISSUE TITLE
As a searcher, I want to apply to a listing using one click, so the lister receives my application. 

### ISSUE THREAD

**Issue by make2002** [sopra-fs23-group-30/sopra-fs23-group-30-server#25]
**Acceptance Criteria**
- By clicking on the “Apply now” button on the search page / listing detail page, an application is created. 
- A modal appears asking the searcher to confirm the decision to apply to the listing. 
- The “Apply now” button changes to “applied” upon successful application. 
- Visual feedback will be given to the searcher. 

**Development Criteria**
- [x] sopra-fs23-group-30/sopra-fs23-group-30-server#26
- [x] sopra-fs23-group-30/sopra-fs23-group-30-server#27
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#17

**Comment by fatihyag** [comment]
fixed with 737536a372ef2fdb70d99f80c104e3d250d9fd71
